# Generated by Django 5.2.8 on 2025-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, default="avatars/default.jpg", upload_to="users/%Y/%m/%d/"
            ),
        ),
    ]
